# Generated by Django 4.2.28 on 2026-02-26 06:58

import candidates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('file_source', models.FileField(upload_to='candidate_files/')),
                ('discovery_datetime', models.DateTimeField(blank=True, null=True)),
                ('real_bogus', models.BooleanField(blank=True, default=None, null=True)),
                ('real_bogus_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tns_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_by_LAST', models.BooleanField(default=False)),
                ('reported_to_astro_colibri', models.BooleanField(default=False)),
                ('host_galaxy', models.CharField(blank=True, max_length=100, null=True)),
                ('dist_Mpc', models.FloatField(null=True)),
                ('redshift', models.FloatField(null=True)),
                ('ToO_name', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, choices=[('stellar', 'Stellar'), ('solar', 'Solar'), ('agn', 'AGN')], default=None, max_length=10, null=True)),
                ('marked_for_followup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePhotometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_date', models.DateTimeField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('magnitude_error', models.FloatField(blank=True, null=True)),
                ('filter_band', models.CharField(blank=True, max_length=20, null=True)),
                ('telescope', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('limit', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photometry', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDataProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(blank=True, null=True, upload_to=candidates.models.candidate_data_product_path)),
                ('data_product_type', models.CharField(choices=[('ref', 'ref'), ('new', 'new'), ('diff', 'diff'), ('ps1', 'ps1'), ('sdss', 'sdss'), ('json', 'json'), ('tns_report', 'tns_report')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_products', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('discovery_datetime', models.DateTimeField(blank=True, null=True)),
                ('fieldid', models.IntegerField(blank=True, null=True)),
                ('subimage', models.IntegerField(blank=True, null=True)),
                ('mount', models.IntegerField(blank=True, null=True)),
                ('camera', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_cutout_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('new_cutout_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('diff_cutout_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='candidates.candidate')),
            ],
        ),
    ]
