# Generated by Django 4.2.17 on 2025-01-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="discovery_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
