# Generated by Django 4.2.17 on 2025-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_candidate_discovery_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="real_bogus",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="dec",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="ra",
            field=models.FloatField(),
        ),
    ]
