# Generated by Django 4.2.17 on 2025-01-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidate_real_bogus_alter_candidate_dec_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidatePhotometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obs_date", models.DateTimeField()),
                ("magnitude", models.FloatField(blank=True, null=True)),
                ("magnitude_error", models.FloatField(blank=True, null=True)),
                ("filter_band", models.CharField(blank=True, max_length=20, null=True)),
                ("telescope", models.CharField(blank=True, max_length=100, null=True)),
                ("instrument", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photometry",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
    ]
