# Generated by Django 4.2.17 on 2025-01-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_candidatephotometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatephotometry",
            name="limit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
