# Generated by Django 4.2.17 on 2025-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0005_candidatephotometry_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="reported_by_LAST",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidate",
            name="tns_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
