# Generated by Django 4.2.17 on 2025-01-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0006_candidate_reported_by_last_candidate_tns_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ingested_candidate_file",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
