# Generated by Django 4.2.17 on 2025-01-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0007_ingested_candidate_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateDataProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datafile", models.FileField(upload_to="data/candidates/None")),
                (
                    "data_product_type",
                    models.CharField(
                        choices=[("cutout", "Cutout"), ("other", "Other")],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_products",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
    ]
