# Generated by Django 4.2.17 on 2025-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0008_candidatedataproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatedataproduct",
            name="data_product_type",
            field=models.CharField(
                choices=[("ref", "ref"), ("new", "new"), ("diff", "diff")],
                max_length=50,
            ),
        ),
    ]
