# Generated by Django 4.2.17 on 2025-01-21 08:17

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0009_alter_candidatedataproduct_data_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatedataproduct",
            name="datafile",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=candidates.models.candidate_data_product_path,
            ),
        ),
    ]
