# Generated by Django 4.2.17 on 2025-01-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0010_alter_candidatedataproduct_datafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatedataproduct",
            name="data_product_type",
            field=models.CharField(
                choices=[
                    ("ref", "ref"),
                    ("new", "new"),
                    ("diff", "diff"),
                    ("ps1", "ps1"),
                ],
                max_length=50,
            ),
        ),
    ]
