# Generated by Django 4.2.17 on 2025-01-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0011_alter_candidatedataproduct_data_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate_alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_datetime", models.DateTimeField(blank=True, null=True)),
                ("fieldid", models.IntegerField()),
                ("subimage", models.IntegerField()),
                ("mount", models.IntegerField()),
                ("camera", models.IntegerField()),
                ("score", models.FloatField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("reference_time", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ingested_candidate_file",
        ),
    ]
