# Generated by Django 4.2.17 on 2025-01-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0012_candidate_alert_delete_ingested_candidate_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Candidate_alert",
            new_name="CandidateAlert",
        ),
    ]
