# Generated by Django 4.2.17 on 2025-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0013_rename_candidate_alert_candidatealert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatealert",
            name="camera",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidatealert",
            name="fieldid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidatealert",
            name="mount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidatealert",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidatealert",
            name="subimage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
