# Generated by Django 4.2.17 on 2025-01-22 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0014_alter_candidatealert_camera_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatealert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
