# Generated by Django 4.2.17 on 2025-01-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0017_candidatealert_diff_cutout_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatedataproduct",
            name="data_product_type",
            field=models.CharField(
                choices=[
                    ("ref", "ref"),
                    ("new", "new"),
                    ("diff", "diff"),
                    ("ps1", "ps1"),
                    ("sdss", "sdss"),
                    ("json", "json"),
                    ("tns_report", "tns_report"),
                ],
                max_length=50,
            ),
        ),
    ]
