# Generated by Django 4.2.17 on 2025-01-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0019_candidate_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="updated_at",
        ),
    ]
