# Generated by Django 4.2.17 on 2025-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0020_remove_candidate_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="real_bogus_user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
