# Generated by Django 4.2.29 on 2026-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidate_real_bogus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ToO_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='classification',
            field=models.CharField(blank=True, choices=[('stellar', 'Stellar'), ('solar', 'Solar'), ('agn', 'AGN')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dist_Mpc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='host_galaxy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marked_for_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='redshift',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reported_to_astro_colibri',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='candidatealert',
            name='filename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidatealert',
            name='reference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
