# Generated by Django 4.2.17 on 2025-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0021_candidate_real_bogus_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="dist_Mpc",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="host_galaxy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
