# Generated by Django 4.2.17 on 2025-04-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0022_candidate_dist_mpc_candidate_host_galaxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="redshift",
            field=models.FloatField(null=True),
        ),
    ]
