# Generated by Django 4.2.17 on 2025-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0023_candidate_redshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="ToO_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
