# Generated by Django 4.2.17 on 2025-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0024_candidate_too_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[("stellar", "Stellar"), ("solar", "Solar"), ("agn", "AGN")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
