# Generated by Django 4.2.17 on 2025-10-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0025_candidate_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="reported_to_astro_colibri",
            field=models.BooleanField(default=False),
        ),
    ]
