# Generated by Django 4.2.17 on 2025-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0026_candidate_reported_to_astro_colibri"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="marked_for_followup",
            field=models.BooleanField(default=False),
        ),
    ]
