# Generated by Django 4.2.29 on 2026-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0029_alter_candidate_name_alter_candidatealert_filename_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['discovery_datetime'], name='candidates__discove_f98332_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatealert',
            index=models.Index(fields=['candidate', '-created_at'], name='candidates__candida_4de5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedataproduct',
            index=models.Index(fields=['candidate', 'data_product_type', '-created_at'], name='candidates__candida_77eb58_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatephotometry',
            index=models.Index(fields=['candidate', 'obs_date'], name='candidates__candida_6aa689_idx'),
        ),
    ]
