"""
Django settings for your TOM project.

Originally generated by 'django-admin startproject' using Django 2.1.1.
Generated by ./manage.py tom_setup on Jan. 18, 2026, 12:23 p.m.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import logging.config
import os
import tempfile
from pathlib import Path
from environ import Env, FileAwareEnv

env = FileAwareEnv()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default: startup fails loudly if SECRET_KEY is missing rather than booting with
# a known, predictable key.
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# No default: fail loudly rather than silently accepting no valid hosts.
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# Optional URL path prefix for serving behind a reverse proxy at e.g. http://host/cast.
# The proxy MUST strip the prefix before forwarding to gunicorn, e.g. nginx:
#     location /cast/ { proxy_pass http://web:8000/; }
# Empty (the default) serves the app at the root.
URL_PREFIX = env.str("URL_PREFIX", default="").rstrip("/")
FORCE_SCRIPT_NAME = URL_PREFIX or None
# Cookies stay at the default path '/' (sent for '/cast/*' too). Scoping them to the
# prefix is unnecessary and can interfere with the login/CSRF flow behind the proxy.


# Application definition

TOM_NAME = 'CAST'

# Use built-in css theme to change the look of your TOM. (Valid themes = [Dark,])
# CSS_THEME = 'Dark'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django_tasks',
    'django_tasks.backends.database',
    'django_tables2',
    'guardian',
    'tom_common',
    'django_comments',
    'bootstrap4',
    'crispy_bootstrap4',
    'crispy_forms',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_gravatar',
    'django_htmx',
    'tom_targets',
    'tom_alerts',
    'tom_catalogs',
    'tom_observations',
    'tom_dataproducts',
    'cast',
    'candidates',
    'FP',
    'LAST',
]

SITE_ID = 1

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'tom_common.middleware.Raise403Middleware',
    'tom_common.middleware.ExternalServiceMiddleware',
    'tom_common.middleware.AuthStrategyMiddleware',
]

ROOT_URLCONF = 'tom_settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'candidates.context_processors.cast_version',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

WSGI_APPLICATION = 'tom_settings.wsgi.application'
ASGI_APPLICATION = 'tom_settings.asgi.application'

COMMENTS_APP = 'django_comments'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env.str("DB_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": env.str("DB_DATABASE", default=BASE_DIR / "db.sqlite3"),
        "USER": env.str("DB_USER", default="user"),
        "PASSWORD": env.str("DB_PASSWORD", default="password"),
        "HOST": env.str("DB_HOST", default="localhost"),
        "PORT": env.str("DB_PORT", default="5432"),
    }
}

# SQLite: wait up to 20s for a write lock (vs the 5s default) before erroring; the
# per-connection PRAGMAs in candidates/models/signals.py enable WAL and further tuning.
if DATABASES["default"]["ENGINE"].endswith("sqlite3"):
    DATABASES["default"].setdefault("OPTIONS", {})["timeout"] = 20

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = f'{URL_PREFIX}/accounts/login/'
LOGIN_REDIRECT_URL = f'{URL_PREFIX}/'
LOGOUT_REDIRECT_URL = f'{URL_PREFIX}/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = f'{URL_PREFIX}/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '_static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'data')
MEDIA_URL = f'{URL_PREFIX}/data/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': env.str('LOG_LEVEL', default='INFO'),
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Caching
# https://docs.djangoproject.com/en/4.2/topics/cache/#filesystem-caching
CACHES = {
    "default": {
        "BACKEND":  env.str("CACHE_BACKEND", default="django.core.cache.backends.filebased.FileBasedCache"),
        "LOCATION": env.str("CACHE_LOCATION", default=tempfile.gettempdir())
    }
}

TASKS = {
    "default": {
        # "BACKEND": "django_tasks.backends.database.DatabaseBackend"
        "BACKEND": "django_tasks.backends.immediate.ImmediateBackend"
    }
}

# TOM Specific configuration
TARGET_TYPE = 'SIDEREAL'

# Set to the full path of a custom target model to extend the BaseTarget Model with custom fields.
# TARGET_MODEL_CLASS = 'marshal_tom_custom.models.UserDefinedTarget'

# Define MATCH_MANAGERS here. This is a dictionary that contains a dotted module path to the desired match manager
# for a given model.
# For example:
# MATCH_MANAGERS = {
#    "Target": "custom_code.match_managers.CustomTargetMatchManager"
# }
MATCH_MANAGERS = {}

FACILITIES = {
    'LCO': {
        'portal_url': 'https://observe.lco.global',
        'api_key': '',
    },
    'GEM': {
        'portal_url': {
            'GS': 'https://139.229.34.15:8443',
            'GN': 'https://128.171.88.221:8443',
        },
        'api_key': {
            'GS': '',
            'GN': '',
        },
        'user_email': '',
        'programs': {
            'GS-YYYYS-T-NNN': {
                'MM': 'Std: Some descriptive text',
                'NN': 'Rap: Some descriptive text'
            },
            'GN-YYYYS-T-NNN': {
                'QQ': 'Std: Some descriptive text',
                'PP': 'Rap: Some descriptive text',
            },
        },
    },
}

# Define the valid data product types for your TOM.
# This is a dictionary of tuples to be used as ChoiceField options, with the first element being the type and the
# second being the display name.
# Be careful when removing items, as previously valid types will no
# longer be valid, and may cause issues unless the offending records are modified.
DATA_PRODUCT_TYPES = {
    'photometry': ('photometry', 'Photometry'),
    'fits_file': ('fits_file', 'FITS File'),
    'spectroscopy': ('spectroscopy', 'Spectroscopy'),
    'image_file': ('image_file', 'Image File')
}

DATA_PROCESSORS = {
    'photometry': 'tom_dataproducts.processors.photometry_processor.PhotometryProcessor',
    'spectroscopy': 'tom_dataproducts.processors.spectroscopy_processor.SpectroscopyProcessor',
}

TOM_FACILITY_CLASSES = [
    'tom_observations.facilities.lco.LCOFacility',
    'tom_observations.facilities.gemini.GEMFacility',
    'tom_observations.facilities.soar.SOARFacility',
    'tom_observations.facilities.blanco.BLANCOFacility',
]

TOM_ALERT_CLASSES = [
    'tom_alerts.brokers.alerce.ALeRCEBroker',
    #  'tom_alerts.brokers.antares.ANTARESBroker',
    'tom_alerts.brokers.gaia.GaiaBroker',
    'tom_alerts.brokers.lasair.LasairBroker',
    'tom_alerts.brokers.tns.TNSBroker',
    #  'tom_alerts.brokers.fink.FinkBroker',
]

BROKERS = {
    'TNS': {
        'api_key': env.str('TNS_API_KEY', default=''),
        'bot_id': env.str('TNS_BOT_ID', default=''),
        'bot_name': env.str('TNS_BOT_NAME', default=''),
    },
    'ATLAS': {
        'api_token': env.str('ATLAS_API_TOKEN', default=''),
    },
    'LASAIR': {
        'api_key': env.str('LASAIR_API_KEY', default=''),
    },
}

LASAIR_API_KEY = env.str('LASAIR_API_KEY', default='')

# Include or exclude specific dot separated harvester classes. If not set, all harvesters will be included based on
# app configurations. If INCLUDE_HARVESTER_CLASSES is set, only those harvesters will be included. If
# EXCLUDE_HARVESTER_CLASSES is set, all harvesters except those will be included.
# INCLUDE_HARVESTER_CLASSES = ['app.example.harvesters.ExampleHarvester']
# EXCLUDE_HARVESTER_CLASSES = ['app.example.harvesters.ExampleHarvester']

HARVESTERS = {
    'TNS': {
        'api_key': ''
    }
}

# Define extra target fields here. Types can be any of "number", "string", "boolean" or "datetime"
# See https://tomtoolkit.github.io/docs/target_fields for documentation on this feature
# For example:
# EXTRA_FIELDS = [
#     {'name': 'redshift', 'type': 'number'},
#     {'name': 'discoverer', 'type': 'string'},
#     {'name': 'eligible', 'type': 'boolean'},
#     {'name': 'discovery_date', 'type': 'datetime'}
# ]
EXTRA_FIELDS = []

# Authentication strategy can either be LOCKED (required login for all views)
# or READ_ONLY (read only access to views)
AUTH_STRATEGY = 'READ_ONLY'

# Row-level data permissions restrict users from viewing certain objects unless they are a member of the group to which
# the object belongs. Setting this value to True will allow all `ObservationRecord`, `DataProduct`, and `ReducedDatum`
# objects to be seen by everyone. Setting it to False will allow users to specify which groups can access
# `ObservationRecord`, `DataProduct`, and `ReducedDatum` objects.
TARGET_PERMISSIONS_ONLY = True

# Default permission for newly created targets. Values can be 'PRIVATE', 'PUBLIC', or 'OPEN'
TARGET_DEFAULT_PERMISSION = 'PRIVATE'

# Display these columns in the target list table. Values can be attributes or properties on
# the Target model, tags or extra fields. The fields `observations` and `saved_data` are
# special cases with custom implementation.
TARGET_LIST_COLUMNS = [
    "name", "type", "observations", "saved_data"
]

# URLs that should be allowed access even with AUTH_STRATEGY = LOCKED
# for example: OPEN_URLS = ['/', '/about']
OPEN_URLS = []

HOOKS = {
    'target_post_save': 'tom_common.hooks.target_post_save',
    'observation_change_state': 'tom_common.hooks.observation_change_state',
    'data_product_post_upload': 'tom_dataproducts.hooks.data_product_post_upload',
    'data_product_post_save': 'tom_dataproducts.hooks.data_product_post_save',
    'multiple_data_products_post_save': 'tom_dataproducts.hooks.multiple_data_products_post_save',
}

AUTO_THUMBNAILS = False

THUMBNAIL_MAX_SIZE = (0, 0)

THUMBNAIL_DEFAULT_SIZE = (200, 200)

HINTS_ENABLED = True
HINT_LEVEL = 20

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}

# Default Plotly theme setting, can set to any valid theme:
# 'plotly', 'plotly_white', 'plotly_dark', 'ggplot2', 'seaborn', 'simple_white', 'none'
PLOTLY_THEME = 'plotly_white'

# Setting for displaying pagination information (e.g., "(0-0 of 0)").
# Set this to False if you have a particularly large DB and paginated views are slow.
SHOW_PAGINATION_INFO = True

try:
    from local_settings import * # noqa
except ImportError:
    pass

# CAST Specific Settings
# Astro-COLIBRI settings
ASTRO_COLIBRI = {
    'api_url': env.str('ASTRO_COLIBRI_API_URL', default='https://astro-colibri.science'),
    'username': env.str('ASTRO_COLIBRI_USERNAME', default='last'),
    'password': env.str('ASTRO_COLIBRI_PASSWORD', default=''),
}

LAST_DB = env.json('LAST_DB', default={
    'host': '',
    'port': 8123,
    'username': '',
    'password': '',
})

FORCED_PHOTOMETRY_DB = env.json('FORCED_PHOTOMETRY_DB', default={
    'host': '',
    'port': 5432,
    'username': '',
    'password': '',
    'CAST_user_id': 0,
})

TRANSIENT_DIR = '/transients'
TNS_TEST = True
TNS_API_LOOKUPS_ENABLED = env.bool('TNS_API_LOOKUPS_ENABLED', default=False)
TNS_PUBLIC_OBJECTS = {
    'url': env.str(
        'TNS_PUBLIC_OBJECTS_URL',
        default='https://www.wis-tns.org/system/files/tns_public_objects/tns_public_objects.csv.zip',
    ),
    'user_agent': env.str(
        'TNS_PUBLIC_OBJECTS_USER_AGENT',
        default='',
    ),
    # A *bot* tns_marker download must POST its api_key (TNS docs); reuse the bot's key.
    'api_key': env.str('TNS_API_KEY', default=''),
    'zip_path': env.str(
        'TNS_PUBLIC_OBJECTS_ZIP_PATH',
        default=str(BASE_DIR / 'large_files' / 'tns' / 'tns_public_objects.csv.zip'),
    ),
    'csv_path': env.str(
        'TNS_PUBLIC_OBJECTS_CSV_PATH',
        default=str(BASE_DIR / 'large_files' / 'tns' / 'tns_public_objects.csv'),
    ),
    'match_radius_arcsec': env.float(
        'TNS_PUBLIC_OBJECTS_MATCH_RADIUS_ARCSEC',
        default=3.0,
    ),
}
# LAST sky fields pickle file path - can be configured via environment variable
LAST_SKY_FIELDS_PKL_PATH = env.str('LAST_SKY_FIELDS_PKL_PATH', default='last/LAST_sky_fields.pkl')

# WhiteNoise static file serving configuration for ASGI
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
# Dev-only: re-stat files on every request. Off in production (static is collected).
WHITENOISE_AUTOREFRESH = env.bool("WHITENOISE_AUTOREFRESH", default=False)
# The reverse proxy strips URL_PREFIX before forwarding, so WhiteNoise matches the
# un-prefixed static path (STATIC_URL carries the prefix only for generated links).
WHITENOISE_STATIC_PREFIX = '/static/'


# CAST Candidates Configuration
# Application version. CalVer scheme "YYYY.MM.DD-N" (build date + same-day build
# number), set per deploy via the CAST_VERSION env var; falls back to "dev".
CAST_VERSION = env.str('CAST_VERSION', default='dev')

CAST_CANDIDATES = {
    # Search and Processing Parameters
    'cone_search_radius_arcsec': env.int('CONE_SEARCH_RADIUS_ARCSEC', default=3),
    'candidate_check_tns_default': env.bool('CANDIDATE_CHECK_TNS_DEFAULT', default=True),

    # Observatory Configuration
    'observatory': {
        'name': env.str('OBSERVATORY_NAME', default='Neot Smadar'),
        'lat': env.float('OBSERVATORY_LAT', default=30.053169),
        'lon': env.float('OBSERVATORY_LON', default=35.041526),
        'alt': env.float('OBSERVATORY_ALT', default=0.405),
    },

    # Horizons API Configuration
    'horizons': {
        'base_url': env.str('HORIZONS_BASE_URL', default='https://ssd-api.jpl.nasa.gov/sb_ident.api'),
        'fov_ra_hwidth': env.float('HORIZONS_FOV_RA_HWIDTH', default=0.27778),
        'fov_dec_hwidth': env.float('HORIZONS_FOV_DEC_HWIDTH', default=0.27778),
        'mag_required': env.bool('HORIZONS_MAG_REQUIRED', default=True),
        'vmag_lim': env.float('HORIZONS_VMAG_LIM', default=22.0),
        'req_elem': env.bool('HORIZONS_REQ_ELEM', default=False),
        'two_pass': env.bool('HORIZONS_TWO_PASS', default=True),
    },

    # PS1 API Configuration
    'ps1': {
        'files_url': env.str('PS1_FILES_URL', default='https://ps1images.stsci.edu/cgi-bin/ps1filenames.py'),
        'cutout_url': env.str('PS1_CUTOUT_URL', default='https://ps1images.stsci.edu/cgi-bin/fitscut.cgi'),
        'timeout': env.int('PS1_REQUEST_TIMEOUT', default=30),
        'image_size': env.int('PS1_IMAGE_SIZE', default=240),
        'autoscale': env.float('PS1_AUTOSCALE', default=99.750000),
    },

    # SDSS API Configuration
    'sdss': {
        'cutout_url': env.str('SDSS_CUTOUT_URL',
                              default='https://skyserver.sdss.org/dr16/SkyServerWS/ImgCutout/getjpeg'),
        'timeout': env.int('SDSS_REQUEST_TIMEOUT', default=30),
        'width': env.int('SDSS_IMAGE_WIDTH', default=240),
        'height': env.int('SDSS_IMAGE_HEIGHT', default=240),
        'scale': env.float('SDSS_IMAGE_SCALE', default=0.2),
    },

    # Instrument Configuration
    'instruments': {
        'last_telescope': env.str('LAST_TELESCOPE_NAME', default='LAST'),
        'last_instrument': env.str('LAST_INSTRUMENT_NAME', default='LAST-CAM'),
        'default_magnitude_error': env.float('DEFAULT_MAGNITUDE_ERROR', default=0.0),
    }
}
